### ISSUE TITLE
Too many cancellations & monotonically increasing CPU usage 

### ISSUE THREAD

**Issue by Dogacel** [fluff-shark/dgs-kotlin-dataloader-example#1]
Hi Dave @fluff-shark , hope you are doing well 🙂 

https://github.com/fluff-shark/dgs-kotlin-dataloader-example/blob/7692b30dbbd7108ef34e31d850a741a8c125bb30/src/main/kotlin/me/fluffshark/dgskotlindataloader/loaders/AbstractCoroutineDataLoader.kt#L34-L81

Recently, we started seeing a pattern in CPU usage, where it increased to some point and never actually dropped down. This caused disruptions in some containers and even required manual intervention of restart of containers.

I suspected this part, because there is a `while` loop and we dispatch jobs. I am afraid DGS is not very good at handling lifecycle of those jobs and loaders. And it is possible that the `while` loop might never terminate under some conditions (i.e. fetch job somehow cancels or wasn't able to populate, maybe there is a `catch` missing... I haven't debugged this very deep.)

So, I have stepped forward and made this change

```kotlin
    override suspend fun load(key: K): V? {
        // Java's Concurrent data structures do not block on reads... so these optimistic reads should be
        // fast and will help minimize locking.
        if (fetchedKeys.contains(key)) {
            return fetchedValues[key]
        }

        // Add the key to the queue of keys to be fetched.
        queuedKeys.add(key)
        return fetchAndReturnValue(key)
    }

    /**
     * We only allow one fetch job to be running at a time. A fetch job loads values based on keys  from queuedKeys into
     * `fetchedValues` and `fetchedKeys`.
     *
     * First, check if value already exists in `fetchedValues`. If it does, return it.
     *
     * If not, check if there is an existing job and wait until it finishes. After it finishes, check if the key is
     * already fetched again. If it is, return its value.
     *
     * If not, start a new job to fetch the key. This time, we should wait for the job to finish before we check if the
     * key is already fetched. If not, it means the key we look for doesn't exist.
     */
    private suspend fun fetchAndReturnValue(key: K): V? = coroutineScope {
        // We use a job lock here to make sure we don't start two fetch jobs at the same time. Also this lock suspends
        // the coroutine until the fetch job is done. So we automatically wait for the fetch job to finish before
        // we check if the key is already fetched.
        fetchJobLock.withLock {
            // If the key is already fetched, return its value.
            if (fetchedKeys.contains(key)) {
                return@coroutineScope fetchedValues[key]
            }

            // If the key is not fetched, it means the key we look for wasn't included in `queuedKeys` when the job
            // started. Thus, we should restart the job with the key we're looking for.
            if (fetchJob.get() != null) {
                // If a job already exists, wait for it to finish before kicking off a new one.
                // Normally, the `fetchJobLock` is released when a job is done. However exceptions or cancellations
                // can cause lock to be released before the job is done. So we need to wait for the job to finish.
                fetchJob.get()?.join()
            }

            // There is a chance that last finished job already fetched the key we're looking for. If so, return its
            // value.
            if (fetchedKeys.contains(key)) {
                return@coroutineScope fetchedValues[key]
            }

            // Start a job that fetches all keys in `queuedKeys` and populates `fetchedKeys` and `fetchedValues`.
            val newJob = launch {
                // 1-millisecond grace period to allow for more keys to be added to `queuedKeys`.
                delay(1)
                // fetchDataLock makes sure we don't load keys twice if `loader.load()` takes longer than `delay()`
                fetchDataLock.withLock {
                    // Take a snapshot of the keys that we are fetching. This is important because we want to remove
                    // the keys from `queuedKeys` only after we have fetched the values for them.
                    val snapshot = queuedKeys.toSet()
                    try {
                        val valueMap = if (snapshot.size >= maxBatchSize) {
                            val batches = snapshot.chunked(maxBatchSize)
                            val values = batches.pmap { doLoad(it.toSet()) }
                            mutableMapOf<K, V>().apply {
                                values.forEach(::putAll)
                            }
                        } else {
                            doLoad(snapshot)
                        }
                        fetchedValues.putAll(valueMap.filterValues { it != null })
                        fetchedKeys.addAll(snapshot)
                    } finally {
                        // If we fail to fetch the values, we should remove the keys from `queuedKeys`. Otherwise,
                        // the keys will be stuck in `queuedKeys` forever.
                        queuedKeys.removeAll(snapshot)
                    }
                }
            }
            // Update the current running fetch job.
            fetchJob.set(newJob)

            // Wait until the job is done
            newJob.join()

            // At this point, our key should be in `fetchedKeys` and we should have its value in `fetchedValues`.
            // If not, it means that there was an error fetching the value and we should return null.
            return@coroutineScope fetchedValues[key]
        }
    }
```

So, most importantly, we don't cancel because cancelling is wasted resources. I.e. if it takes X amount of time to fetch something, if we do the cancel strategy, it is possible that we might cancel the operation at %60, %90 probability. After the change where we don't cancel but we queue everything that is waiting, thus our worst case becomes 2X time and best case still X. I haven't really digged the numbers however it feels like this is safer and it also resolved the CPU spikes (for now) 😆 

Wanted to mention the issue here as well so if anyone needs to use the same thing with DGS, they don't have to worry about this 🙂

**Comment by fluff-shark** [comment]
Makes sense, and thanks! Always good to know how these sorts of things hold up after the fact. Hope you're doing well too.

Depending on peoples' use-cases, this may be a little risky:

> // If not, it means that there was an error fetching the value and we should return null.

returning null will swallow the error, which locks Resolvers out of any custom error handling. It can be risky to do that in a centralized util like this because you never know what those future use-cases will be, and if one of them _needs_ custom error handling it'd be a very risky change (since all the Resolvers written in the meantime are written expecting the `null` return). It's probably better to find some way to pass the error up the chain so callers can decide what to do with it.

-----------------
I do think it's an improvement on balance though, so I copy/pushed those changes in https://github.com/fluff-shark/dgs-kotlin-dataloader-example/commit/535db2d3c3da8c3e627370355520c10fd42aa7a8 so others have the most up-to-date version.

**Comment by fluff-shark** [comment]
Makes sense, and thanks @Dogacel! Always good to know how these sorts of things hold up after the fact. Hope you're doing well too.

Something is a bit fishy about this:

> // If not, it means that there was an error fetching the value and we should return null.

I didn't debug either... but there's a test for that in https://github.com/fluff-shark/dgs-kotlin-dataloader-example/blob/468394d3169ba548f1b86152963d13f3c7f984d0/src/test/kotlin/me/fluffshark/dgskotlindataloader/loaders/CoroutineMappedBatchLoaderAdapterTest.kt#L132 -- errors from the underlying loader are bubbled up, and the test still passes against your impl.

Either way, I copy/pushed those changes in https://github.com/fluff-shark/dgs-kotlin-dataloader-example/commit/535db2d3c3da8c3e627370355520c10fd42aa7a8 so others have the most up-to-date version. Thanks for the contribution!
